image: ubuntu:16.04
#image: node:6    # specify your Docker image here

pipelines:
    branches:
        master:
            - step:
                script:
                    - apt-get -y update && apt-get -y upgrade && apt-get -y install ssh && apt-get -y install git
                    - mkdir -p ~/.ssh
                    - cat known_hosts >> ~/.ssh/known_hosts
                    - (umask  077 ; echo $KEY_RSA_BASE64 | base64 --decode > ~/.ssh/id_rsa)
                    - ssh $DOMAIN_USER@$DOMAIN_IP git clone --single-branch -b master https://$MAX_GIT_USER:$MAX_GIT_USER_PASS@bitbucket.org/inoxoft/hubhotels.git $MASTER_FOLDER
#                    - ssh $DOMAIN_USER@$DOMAIN_IP cd $MASTER_FOLDER && composer istall
